<?php

namespace AdAstra\Support\Iso;

/**
 * ISO 3166-2 subdivision reference data.
 *
 * Practical first-cut coverage for the State/Province field. Codes follow
 * the ISO 3166-2 form (e.g. "US-CA", "CA-ON"). Adding more countries later
 * is purely a data-file edit.
 *
 * Covered: US, CA, MX, GB, IE, AU, NZ, DE, FR, ES, IT, NL, BE, BR, IN, JP, CN.
 */
final class Subdivisions
{
    /**
     * @return list<array{code: string, name: string}>
     */
    public static function forCountry(string $countryCode): array
    {
        return self::DATA[strtoupper($countryCode)] ?? [];
    }

    public static function exists(string $countryCode, string $subdivisionCode): bool
    {
        $list = self::forCountry($countryCode);
        $needle = strtoupper($subdivisionCode);
        foreach ($list as $entry) {
            if (strtoupper($entry['code']) === $needle) {
                return true;
            }
        }
        return false;
    }

    public static function hasData(string $countryCode): bool
    {
        return !empty(self::DATA[strtoupper($countryCode)] ?? null);
    }

    public static function name(string $countryCode, string $subdivisionCode): string
    {
        $list = self::forCountry($countryCode);
        $needle = strtoupper($subdivisionCode);
        foreach ($list as $entry) {
            if (strtoupper($entry['code']) === $needle) {
                return $entry['name'];
            }
        }
        return $subdivisionCode;
    }

    private const DATA = [
        'US' => [
            ['code' => 'US-AL', 'name' => 'Alabama'],
            ['code' => 'US-AK', 'name' => 'Alaska'],
            ['code' => 'US-AZ', 'name' => 'Arizona'],
            ['code' => 'US-AR', 'name' => 'Arkansas'],
            ['code' => 'US-CA', 'name' => 'California'],
            ['code' => 'US-CO', 'name' => 'Colorado'],
            ['code' => 'US-CT', 'name' => 'Connecticut'],
            ['code' => 'US-DE', 'name' => 'Delaware'],
            ['code' => 'US-DC', 'name' => 'District of Columbia'],
            ['code' => 'US-FL', 'name' => 'Florida'],
            ['code' => 'US-GA', 'name' => 'Georgia'],
            ['code' => 'US-HI', 'name' => 'Hawaii'],
            ['code' => 'US-ID', 'name' => 'Idaho'],
            ['code' => 'US-IL', 'name' => 'Illinois'],
            ['code' => 'US-IN', 'name' => 'Indiana'],
            ['code' => 'US-IA', 'name' => 'Iowa'],
            ['code' => 'US-KS', 'name' => 'Kansas'],
            ['code' => 'US-KY', 'name' => 'Kentucky'],
            ['code' => 'US-LA', 'name' => 'Louisiana'],
            ['code' => 'US-ME', 'name' => 'Maine'],
            ['code' => 'US-MD', 'name' => 'Maryland'],
            ['code' => 'US-MA', 'name' => 'Massachusetts'],
            ['code' => 'US-MI', 'name' => 'Michigan'],
            ['code' => 'US-MN', 'name' => 'Minnesota'],
            ['code' => 'US-MS', 'name' => 'Mississippi'],
            ['code' => 'US-MO', 'name' => 'Missouri'],
            ['code' => 'US-MT', 'name' => 'Montana'],
            ['code' => 'US-NE', 'name' => 'Nebraska'],
            ['code' => 'US-NV', 'name' => 'Nevada'],
            ['code' => 'US-NH', 'name' => 'New Hampshire'],
            ['code' => 'US-NJ', 'name' => 'New Jersey'],
            ['code' => 'US-NM', 'name' => 'New Mexico'],
            ['code' => 'US-NY', 'name' => 'New York'],
            ['code' => 'US-NC', 'name' => 'North Carolina'],
            ['code' => 'US-ND', 'name' => 'North Dakota'],
            ['code' => 'US-OH', 'name' => 'Ohio'],
            ['code' => 'US-OK', 'name' => 'Oklahoma'],
            ['code' => 'US-OR', 'name' => 'Oregon'],
            ['code' => 'US-PA', 'name' => 'Pennsylvania'],
            ['code' => 'US-RI', 'name' => 'Rhode Island'],
            ['code' => 'US-SC', 'name' => 'South Carolina'],
            ['code' => 'US-SD', 'name' => 'South Dakota'],
            ['code' => 'US-TN', 'name' => 'Tennessee'],
            ['code' => 'US-TX', 'name' => 'Texas'],
            ['code' => 'US-UT', 'name' => 'Utah'],
            ['code' => 'US-VT', 'name' => 'Vermont'],
            ['code' => 'US-VA', 'name' => 'Virginia'],
            ['code' => 'US-WA', 'name' => 'Washington'],
            ['code' => 'US-WV', 'name' => 'West Virginia'],
            ['code' => 'US-WI', 'name' => 'Wisconsin'],
            ['code' => 'US-WY', 'name' => 'Wyoming'],
            ['code' => 'US-AS', 'name' => 'American Samoa'],
            ['code' => 'US-GU', 'name' => 'Guam'],
            ['code' => 'US-MP', 'name' => 'Northern Mariana Islands'],
            ['code' => 'US-PR', 'name' => 'Puerto Rico'],
            ['code' => 'US-VI', 'name' => 'United States Virgin Islands'],
        ],
        'CA' => [
            ['code' => 'CA-AB', 'name' => 'Alberta'],
            ['code' => 'CA-BC', 'name' => 'British Columbia'],
            ['code' => 'CA-MB', 'name' => 'Manitoba'],
            ['code' => 'CA-NB', 'name' => 'New Brunswick'],
            ['code' => 'CA-NL', 'name' => 'Newfoundland and Labrador'],
            ['code' => 'CA-NS', 'name' => 'Nova Scotia'],
            ['code' => 'CA-ON', 'name' => 'Ontario'],
            ['code' => 'CA-PE', 'name' => 'Prince Edward Island'],
            ['code' => 'CA-QC', 'name' => 'Quebec'],
            ['code' => 'CA-SK', 'name' => 'Saskatchewan'],
            ['code' => 'CA-NT', 'name' => 'Northwest Territories'],
            ['code' => 'CA-NU', 'name' => 'Nunavut'],
            ['code' => 'CA-YT', 'name' => 'Yukon'],
        ],
        'MX' => [
            ['code' => 'MX-AGU', 'name' => 'Aguascalientes'],
            ['code' => 'MX-BCN', 'name' => 'Baja California'],
            ['code' => 'MX-BCS', 'name' => 'Baja California Sur'],
            ['code' => 'MX-CAM', 'name' => 'Campeche'],
            ['code' => 'MX-CHP', 'name' => 'Chiapas'],
            ['code' => 'MX-CHH', 'name' => 'Chihuahua'],
            ['code' => 'MX-CMX', 'name' => 'Ciudad de México'],
            ['code' => 'MX-COA', 'name' => 'Coahuila de Zaragoza'],
            ['code' => 'MX-COL', 'name' => 'Colima'],
            ['code' => 'MX-DUR', 'name' => 'Durango'],
            ['code' => 'MX-GUA', 'name' => 'Guanajuato'],
            ['code' => 'MX-GRO', 'name' => 'Guerrero'],
            ['code' => 'MX-HID', 'name' => 'Hidalgo'],
            ['code' => 'MX-JAL', 'name' => 'Jalisco'],
            ['code' => 'MX-MEX', 'name' => 'México'],
            ['code' => 'MX-MIC', 'name' => 'Michoacán de Ocampo'],
            ['code' => 'MX-MOR', 'name' => 'Morelos'],
            ['code' => 'MX-NAY', 'name' => 'Nayarit'],
            ['code' => 'MX-NLE', 'name' => 'Nuevo León'],
            ['code' => 'MX-OAX', 'name' => 'Oaxaca'],
            ['code' => 'MX-PUE', 'name' => 'Puebla'],
            ['code' => 'MX-QUE', 'name' => 'Querétaro'],
            ['code' => 'MX-ROO', 'name' => 'Quintana Roo'],
            ['code' => 'MX-SLP', 'name' => 'San Luis Potosí'],
            ['code' => 'MX-SIN', 'name' => 'Sinaloa'],
            ['code' => 'MX-SON', 'name' => 'Sonora'],
            ['code' => 'MX-TAB', 'name' => 'Tabasco'],
            ['code' => 'MX-TAM', 'name' => 'Tamaulipas'],
            ['code' => 'MX-TLA', 'name' => 'Tlaxcala'],
            ['code' => 'MX-VER', 'name' => 'Veracruz de Ignacio de la Llave'],
            ['code' => 'MX-YUC', 'name' => 'Yucatán'],
            ['code' => 'MX-ZAC', 'name' => 'Zacatecas'],
        ],
        'GB' => [
            ['code' => 'GB-ENG', 'name' => 'England'],
            ['code' => 'GB-SCT', 'name' => 'Scotland'],
            ['code' => 'GB-WLS', 'name' => 'Wales'],
            ['code' => 'GB-NIR', 'name' => 'Northern Ireland'],
        ],
        'IE' => [
            ['code' => 'IE-CW', 'name' => 'Carlow'],
            ['code' => 'IE-CN', 'name' => 'Cavan'],
            ['code' => 'IE-CE', 'name' => 'Clare'],
            ['code' => 'IE-CO', 'name' => 'Cork'],
            ['code' => 'IE-DL', 'name' => 'Donegal'],
            ['code' => 'IE-D', 'name' => 'Dublin'],
            ['code' => 'IE-G', 'name' => 'Galway'],
            ['code' => 'IE-KY', 'name' => 'Kerry'],
            ['code' => 'IE-KE', 'name' => 'Kildare'],
            ['code' => 'IE-KK', 'name' => 'Kilkenny'],
            ['code' => 'IE-LS', 'name' => 'Laois'],
            ['code' => 'IE-LM', 'name' => 'Leitrim'],
            ['code' => 'IE-LK', 'name' => 'Limerick'],
            ['code' => 'IE-LD', 'name' => 'Longford'],
            ['code' => 'IE-LH', 'name' => 'Louth'],
            ['code' => 'IE-MO', 'name' => 'Mayo'],
            ['code' => 'IE-MH', 'name' => 'Meath'],
            ['code' => 'IE-MN', 'name' => 'Monaghan'],
            ['code' => 'IE-OY', 'name' => 'Offaly'],
            ['code' => 'IE-RN', 'name' => 'Roscommon'],
            ['code' => 'IE-SO', 'name' => 'Sligo'],
            ['code' => 'IE-TA', 'name' => 'Tipperary'],
            ['code' => 'IE-WD', 'name' => 'Waterford'],
            ['code' => 'IE-WH', 'name' => 'Westmeath'],
            ['code' => 'IE-WX', 'name' => 'Wexford'],
            ['code' => 'IE-WW', 'name' => 'Wicklow'],
        ],
        'AU' => [
            ['code' => 'AU-NSW', 'name' => 'New South Wales'],
            ['code' => 'AU-VIC', 'name' => 'Victoria'],
            ['code' => 'AU-QLD', 'name' => 'Queensland'],
            ['code' => 'AU-WA', 'name' => 'Western Australia'],
            ['code' => 'AU-SA', 'name' => 'South Australia'],
            ['code' => 'AU-TAS', 'name' => 'Tasmania'],
            ['code' => 'AU-ACT', 'name' => 'Australian Capital Territory'],
            ['code' => 'AU-NT', 'name' => 'Northern Territory'],
        ],
        'NZ' => [
            ['code' => 'NZ-AUK', 'name' => 'Auckland'],
            ['code' => 'NZ-BOP', 'name' => 'Bay of Plenty'],
            ['code' => 'NZ-CAN', 'name' => 'Canterbury'],
            ['code' => 'NZ-GIS', 'name' => 'Gisborne'],
            ['code' => 'NZ-HKB', 'name' => "Hawke's Bay"],
            ['code' => 'NZ-MWT', 'name' => 'Manawatū-Whanganui'],
            ['code' => 'NZ-MBH', 'name' => 'Marlborough'],
            ['code' => 'NZ-NSN', 'name' => 'Nelson'],
            ['code' => 'NZ-NTL', 'name' => 'Northland'],
            ['code' => 'NZ-OTA', 'name' => 'Otago'],
            ['code' => 'NZ-STL', 'name' => 'Southland'],
            ['code' => 'NZ-TKI', 'name' => 'Taranaki'],
            ['code' => 'NZ-TAS', 'name' => 'Tasman'],
            ['code' => 'NZ-WKO', 'name' => 'Waikato'],
            ['code' => 'NZ-WGN', 'name' => 'Wellington'],
            ['code' => 'NZ-WTC', 'name' => 'West Coast'],
            ['code' => 'NZ-CIT', 'name' => 'Chatham Islands Territory'],
        ],
        'DE' => [
            ['code' => 'DE-BW', 'name' => 'Baden-Württemberg'],
            ['code' => 'DE-BY', 'name' => 'Bayern'],
            ['code' => 'DE-BE', 'name' => 'Berlin'],
            ['code' => 'DE-BB', 'name' => 'Brandenburg'],
            ['code' => 'DE-HB', 'name' => 'Bremen'],
            ['code' => 'DE-HH', 'name' => 'Hamburg'],
            ['code' => 'DE-HE', 'name' => 'Hessen'],
            ['code' => 'DE-MV', 'name' => 'Mecklenburg-Vorpommern'],
            ['code' => 'DE-NI', 'name' => 'Niedersachsen'],
            ['code' => 'DE-NW', 'name' => 'Nordrhein-Westfalen'],
            ['code' => 'DE-RP', 'name' => 'Rheinland-Pfalz'],
            ['code' => 'DE-SL', 'name' => 'Saarland'],
            ['code' => 'DE-SN', 'name' => 'Sachsen'],
            ['code' => 'DE-ST', 'name' => 'Sachsen-Anhalt'],
            ['code' => 'DE-SH', 'name' => 'Schleswig-Holstein'],
            ['code' => 'DE-TH', 'name' => 'Thüringen'],
        ],
        'FR' => [
            ['code' => 'FR-ARA', 'name' => 'Auvergne-Rhône-Alpes'],
            ['code' => 'FR-BFC', 'name' => 'Bourgogne-Franche-Comté'],
            ['code' => 'FR-BRE', 'name' => 'Bretagne'],
            ['code' => 'FR-CVL', 'name' => 'Centre-Val de Loire'],
            ['code' => 'FR-20R', 'name' => 'Corse'],
            ['code' => 'FR-GES', 'name' => 'Grand Est'],
            ['code' => 'FR-HDF', 'name' => 'Hauts-de-France'],
            ['code' => 'FR-IDF', 'name' => 'Île-de-France'],
            ['code' => 'FR-NOR', 'name' => 'Normandie'],
            ['code' => 'FR-NAQ', 'name' => 'Nouvelle-Aquitaine'],
            ['code' => 'FR-OCC', 'name' => 'Occitanie'],
            ['code' => 'FR-PDL', 'name' => 'Pays de la Loire'],
            ['code' => 'FR-PAC', 'name' => "Provence-Alpes-Côte d'Azur"],
            ['code' => 'FR-GUA', 'name' => 'Guadeloupe'],
            ['code' => 'FR-GF', 'name' => 'Guyane'],
            ['code' => 'FR-MQ', 'name' => 'Martinique'],
            ['code' => 'FR-LRE', 'name' => 'La Réunion'],
            ['code' => 'FR-MAY', 'name' => 'Mayotte'],
        ],
        'ES' => [
            ['code' => 'ES-AN', 'name' => 'Andalucía'],
            ['code' => 'ES-AR', 'name' => 'Aragón'],
            ['code' => 'ES-AS', 'name' => 'Asturias, Principado de'],
            ['code' => 'ES-CN', 'name' => 'Canarias'],
            ['code' => 'ES-CB', 'name' => 'Cantabria'],
            ['code' => 'ES-CM', 'name' => 'Castilla-La Mancha'],
            ['code' => 'ES-CL', 'name' => 'Castilla y León'],
            ['code' => 'ES-CT', 'name' => 'Cataluña'],
            ['code' => 'ES-EX', 'name' => 'Extremadura'],
            ['code' => 'ES-GA', 'name' => 'Galicia'],
            ['code' => 'ES-IB', 'name' => 'Illes Balears'],
            ['code' => 'ES-RI', 'name' => 'La Rioja'],
            ['code' => 'ES-MD', 'name' => 'Madrid, Comunidad de'],
            ['code' => 'ES-MC', 'name' => 'Murcia, Región de'],
            ['code' => 'ES-NC', 'name' => 'Navarra, Comunidad Foral de'],
            ['code' => 'ES-PV', 'name' => 'País Vasco'],
            ['code' => 'ES-VC', 'name' => 'Valenciana, Comunidad'],
            ['code' => 'ES-CE', 'name' => 'Ceuta'],
            ['code' => 'ES-ML', 'name' => 'Melilla'],
        ],
        'IT' => [
            ['code' => 'IT-65', 'name' => 'Abruzzo'],
            ['code' => 'IT-77', 'name' => 'Basilicata'],
            ['code' => 'IT-78', 'name' => 'Calabria'],
            ['code' => 'IT-72', 'name' => 'Campania'],
            ['code' => 'IT-45', 'name' => 'Emilia-Romagna'],
            ['code' => 'IT-36', 'name' => 'Friuli Venezia Giulia'],
            ['code' => 'IT-62', 'name' => 'Lazio'],
            ['code' => 'IT-42', 'name' => 'Liguria'],
            ['code' => 'IT-25', 'name' => 'Lombardia'],
            ['code' => 'IT-57', 'name' => 'Marche'],
            ['code' => 'IT-67', 'name' => 'Molise'],
            ['code' => 'IT-21', 'name' => 'Piemonte'],
            ['code' => 'IT-75', 'name' => 'Puglia'],
            ['code' => 'IT-88', 'name' => 'Sardegna'],
            ['code' => 'IT-82', 'name' => 'Sicilia'],
            ['code' => 'IT-52', 'name' => 'Toscana'],
            ['code' => 'IT-32', 'name' => 'Trentino-Alto Adige'],
            ['code' => 'IT-55', 'name' => 'Umbria'],
            ['code' => 'IT-23', 'name' => "Valle d'Aosta"],
            ['code' => 'IT-34', 'name' => 'Veneto'],
        ],
        'NL' => [
            ['code' => 'NL-DR', 'name' => 'Drenthe'],
            ['code' => 'NL-FL', 'name' => 'Flevoland'],
            ['code' => 'NL-FR', 'name' => 'Fryslân'],
            ['code' => 'NL-GE', 'name' => 'Gelderland'],
            ['code' => 'NL-GR', 'name' => 'Groningen'],
            ['code' => 'NL-LI', 'name' => 'Limburg'],
            ['code' => 'NL-NB', 'name' => 'Noord-Brabant'],
            ['code' => 'NL-NH', 'name' => 'Noord-Holland'],
            ['code' => 'NL-OV', 'name' => 'Overijssel'],
            ['code' => 'NL-UT', 'name' => 'Utrecht'],
            ['code' => 'NL-ZE', 'name' => 'Zeeland'],
            ['code' => 'NL-ZH', 'name' => 'Zuid-Holland'],
        ],
        'BE' => [
            ['code' => 'BE-BRU', 'name' => 'Brussels-Capital Region'],
            ['code' => 'BE-VAN', 'name' => 'Antwerpen'],
            ['code' => 'BE-VBR', 'name' => 'Vlaams-Brabant'],
            ['code' => 'BE-VLI', 'name' => 'Limburg'],
            ['code' => 'BE-VOV', 'name' => 'Oost-Vlaanderen'],
            ['code' => 'BE-VWV', 'name' => 'West-Vlaanderen'],
            ['code' => 'BE-WBR', 'name' => 'Brabant wallon'],
            ['code' => 'BE-WHT', 'name' => 'Hainaut'],
            ['code' => 'BE-WLG', 'name' => 'Liège'],
            ['code' => 'BE-WLX', 'name' => 'Luxembourg'],
            ['code' => 'BE-WNA', 'name' => 'Namur'],
        ],
        'BR' => [
            ['code' => 'BR-AC', 'name' => 'Acre'],
            ['code' => 'BR-AL', 'name' => 'Alagoas'],
            ['code' => 'BR-AP', 'name' => 'Amapá'],
            ['code' => 'BR-AM', 'name' => 'Amazonas'],
            ['code' => 'BR-BA', 'name' => 'Bahia'],
            ['code' => 'BR-CE', 'name' => 'Ceará'],
            ['code' => 'BR-DF', 'name' => 'Distrito Federal'],
            ['code' => 'BR-ES', 'name' => 'Espírito Santo'],
            ['code' => 'BR-GO', 'name' => 'Goiás'],
            ['code' => 'BR-MA', 'name' => 'Maranhão'],
            ['code' => 'BR-MT', 'name' => 'Mato Grosso'],
            ['code' => 'BR-MS', 'name' => 'Mato Grosso do Sul'],
            ['code' => 'BR-MG', 'name' => 'Minas Gerais'],
            ['code' => 'BR-PA', 'name' => 'Pará'],
            ['code' => 'BR-PB', 'name' => 'Paraíba'],
            ['code' => 'BR-PR', 'name' => 'Paraná'],
            ['code' => 'BR-PE', 'name' => 'Pernambuco'],
            ['code' => 'BR-PI', 'name' => 'Piauí'],
            ['code' => 'BR-RJ', 'name' => 'Rio de Janeiro'],
            ['code' => 'BR-RN', 'name' => 'Rio Grande do Norte'],
            ['code' => 'BR-RS', 'name' => 'Rio Grande do Sul'],
            ['code' => 'BR-RO', 'name' => 'Rondônia'],
            ['code' => 'BR-RR', 'name' => 'Roraima'],
            ['code' => 'BR-SC', 'name' => 'Santa Catarina'],
            ['code' => 'BR-SP', 'name' => 'São Paulo'],
            ['code' => 'BR-SE', 'name' => 'Sergipe'],
            ['code' => 'BR-TO', 'name' => 'Tocantins'],
        ],
        'IN' => [
            ['code' => 'IN-AP', 'name' => 'Andhra Pradesh'],
            ['code' => 'IN-AR', 'name' => 'Arunachal Pradesh'],
            ['code' => 'IN-AS', 'name' => 'Assam'],
            ['code' => 'IN-BR', 'name' => 'Bihar'],
            ['code' => 'IN-CT', 'name' => 'Chhattisgarh'],
            ['code' => 'IN-GA', 'name' => 'Goa'],
            ['code' => 'IN-GJ', 'name' => 'Gujarat'],
            ['code' => 'IN-HR', 'name' => 'Haryana'],
            ['code' => 'IN-HP', 'name' => 'Himachal Pradesh'],
            ['code' => 'IN-JH', 'name' => 'Jharkhand'],
            ['code' => 'IN-KA', 'name' => 'Karnataka'],
            ['code' => 'IN-KL', 'name' => 'Kerala'],
            ['code' => 'IN-MP', 'name' => 'Madhya Pradesh'],
            ['code' => 'IN-MH', 'name' => 'Maharashtra'],
            ['code' => 'IN-MN', 'name' => 'Manipur'],
            ['code' => 'IN-ML', 'name' => 'Meghalaya'],
            ['code' => 'IN-MZ', 'name' => 'Mizoram'],
            ['code' => 'IN-NL', 'name' => 'Nagaland'],
            ['code' => 'IN-OR', 'name' => 'Odisha'],
            ['code' => 'IN-PB', 'name' => 'Punjab'],
            ['code' => 'IN-RJ', 'name' => 'Rajasthan'],
            ['code' => 'IN-SK', 'name' => 'Sikkim'],
            ['code' => 'IN-TN', 'name' => 'Tamil Nadu'],
            ['code' => 'IN-TG', 'name' => 'Telangana'],
            ['code' => 'IN-TR', 'name' => 'Tripura'],
            ['code' => 'IN-UP', 'name' => 'Uttar Pradesh'],
            ['code' => 'IN-UT', 'name' => 'Uttarakhand'],
            ['code' => 'IN-WB', 'name' => 'West Bengal'],
            ['code' => 'IN-AN', 'name' => 'Andaman and Nicobar Islands'],
            ['code' => 'IN-CH', 'name' => 'Chandigarh'],
            ['code' => 'IN-DH', 'name' => 'Dadra and Nagar Haveli and Daman and Diu'],
            ['code' => 'IN-DL', 'name' => 'Delhi'],
            ['code' => 'IN-JK', 'name' => 'Jammu and Kashmir'],
            ['code' => 'IN-LA', 'name' => 'Ladakh'],
            ['code' => 'IN-LD', 'name' => 'Lakshadweep'],
            ['code' => 'IN-PY', 'name' => 'Puducherry'],
        ],
        'JP' => [
            ['code' => 'JP-01', 'name' => 'Hokkaido'],
            ['code' => 'JP-02', 'name' => 'Aomori'],
            ['code' => 'JP-03', 'name' => 'Iwate'],
            ['code' => 'JP-04', 'name' => 'Miyagi'],
            ['code' => 'JP-05', 'name' => 'Akita'],
            ['code' => 'JP-06', 'name' => 'Yamagata'],
            ['code' => 'JP-07', 'name' => 'Fukushima'],
            ['code' => 'JP-08', 'name' => 'Ibaraki'],
            ['code' => 'JP-09', 'name' => 'Tochigi'],
            ['code' => 'JP-10', 'name' => 'Gunma'],
            ['code' => 'JP-11', 'name' => 'Saitama'],
            ['code' => 'JP-12', 'name' => 'Chiba'],
            ['code' => 'JP-13', 'name' => 'Tokyo'],
            ['code' => 'JP-14', 'name' => 'Kanagawa'],
            ['code' => 'JP-15', 'name' => 'Niigata'],
            ['code' => 'JP-16', 'name' => 'Toyama'],
            ['code' => 'JP-17', 'name' => 'Ishikawa'],
            ['code' => 'JP-18', 'name' => 'Fukui'],
            ['code' => 'JP-19', 'name' => 'Yamanashi'],
            ['code' => 'JP-20', 'name' => 'Nagano'],
            ['code' => 'JP-21', 'name' => 'Gifu'],
            ['code' => 'JP-22', 'name' => 'Shizuoka'],
            ['code' => 'JP-23', 'name' => 'Aichi'],
            ['code' => 'JP-24', 'name' => 'Mie'],
            ['code' => 'JP-25', 'name' => 'Shiga'],
            ['code' => 'JP-26', 'name' => 'Kyoto'],
            ['code' => 'JP-27', 'name' => 'Osaka'],
            ['code' => 'JP-28', 'name' => 'Hyogo'],
            ['code' => 'JP-29', 'name' => 'Nara'],
            ['code' => 'JP-30', 'name' => 'Wakayama'],
            ['code' => 'JP-31', 'name' => 'Tottori'],
            ['code' => 'JP-32', 'name' => 'Shimane'],
            ['code' => 'JP-33', 'name' => 'Okayama'],
            ['code' => 'JP-34', 'name' => 'Hiroshima'],
            ['code' => 'JP-35', 'name' => 'Yamaguchi'],
            ['code' => 'JP-36', 'name' => 'Tokushima'],
            ['code' => 'JP-37', 'name' => 'Kagawa'],
            ['code' => 'JP-38', 'name' => 'Ehime'],
            ['code' => 'JP-39', 'name' => 'Kochi'],
            ['code' => 'JP-40', 'name' => 'Fukuoka'],
            ['code' => 'JP-41', 'name' => 'Saga'],
            ['code' => 'JP-42', 'name' => 'Nagasaki'],
            ['code' => 'JP-43', 'name' => 'Kumamoto'],
            ['code' => 'JP-44', 'name' => 'Oita'],
            ['code' => 'JP-45', 'name' => 'Miyazaki'],
            ['code' => 'JP-46', 'name' => 'Kagoshima'],
            ['code' => 'JP-47', 'name' => 'Okinawa'],
        ],
        'CN' => [
            ['code' => 'CN-BJ', 'name' => 'Beijing'],
            ['code' => 'CN-TJ', 'name' => 'Tianjin'],
            ['code' => 'CN-HE', 'name' => 'Hebei'],
            ['code' => 'CN-SX', 'name' => 'Shanxi'],
            ['code' => 'CN-NM', 'name' => 'Nei Mongol'],
            ['code' => 'CN-LN', 'name' => 'Liaoning'],
            ['code' => 'CN-JL', 'name' => 'Jilin'],
            ['code' => 'CN-HL', 'name' => 'Heilongjiang'],
            ['code' => 'CN-SH', 'name' => 'Shanghai'],
            ['code' => 'CN-JS', 'name' => 'Jiangsu'],
            ['code' => 'CN-ZJ', 'name' => 'Zhejiang'],
            ['code' => 'CN-AH', 'name' => 'Anhui'],
            ['code' => 'CN-FJ', 'name' => 'Fujian'],
            ['code' => 'CN-JX', 'name' => 'Jiangxi'],
            ['code' => 'CN-SD', 'name' => 'Shandong'],
            ['code' => 'CN-HA', 'name' => 'Henan'],
            ['code' => 'CN-HB', 'name' => 'Hubei'],
            ['code' => 'CN-HN', 'name' => 'Hunan'],
            ['code' => 'CN-GD', 'name' => 'Guangdong'],
            ['code' => 'CN-GX', 'name' => 'Guangxi'],
            ['code' => 'CN-HI', 'name' => 'Hainan'],
            ['code' => 'CN-CQ', 'name' => 'Chongqing'],
            ['code' => 'CN-SC', 'name' => 'Sichuan'],
            ['code' => 'CN-GZ', 'name' => 'Guizhou'],
            ['code' => 'CN-YN', 'name' => 'Yunnan'],
            ['code' => 'CN-XZ', 'name' => 'Xizang'],
            ['code' => 'CN-SN', 'name' => 'Shaanxi'],
            ['code' => 'CN-GS', 'name' => 'Gansu'],
            ['code' => 'CN-QH', 'name' => 'Qinghai'],
            ['code' => 'CN-NX', 'name' => 'Ningxia'],
            ['code' => 'CN-XJ', 'name' => 'Xinjiang'],
            ['code' => 'CN-TW', 'name' => 'Taiwan'],
            ['code' => 'CN-HK', 'name' => 'Hong Kong'],
            ['code' => 'CN-MO', 'name' => 'Macao'],
        ],
    ];
}
